### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by BTUJACK** [weiensong/pond-loach#1]
hi 非常感谢您的分享，我完全按照您的指引下载了对应的库，运行代码报错了，您有空帮忙看看吗？

`C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.20) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 458, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 502, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1046, in _create
    self.do_handshake()
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1317, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.fortunechina.com', port=443): Max retries exceeded with url: /fortune500/c/2021-08/02/content_394571.htm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\500ǿ��˾\crawler.py", line 51, in <module>
    crawler()
  File "D:\python\500ǿ��˾\crawler.py", line 23, in crawler
    response = requests.get(url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.fortunechina.com', port=443): Max retries exceeded with url: /fortune500/c/2021-08/02/content_394571.htm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
[Finished in 1.5s with exit code 1]
[cmd: ['C:/Users/Z003TESJ/AppData/Local/Programs/Python/Python312/python.exe', '-u', 'D:\\python\\500强公司\\crawler.py']]
[dir: D:\python\500强公司]
[path: C:\Program Files\Zulu\zulu-8-jre\bin\;C:\Program Files (x86)\Zulu\zulu-8-jre\bin\;C:\Program Files\IcedTeaWeb\WebStart\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Files\fortran\bin\ia32;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\Z003TESJ\AppData\Local\Programs\Python\Python312\;D:\Program Files\Python3.5.1\Scripts\;D:\Program Files\Python3.5.1\;C:\Users\Z003TESJ\AppData\Local\Microsoft\WindowsApps;;D:\Program Files\Microsoft VS Code\bin]`

**Comment by BTUJACK** [comment]
我解决了这个问题，通过更新库。
urllib3 (1.26.20) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

**Comment by BTUJACK** [comment]
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)这个问题搞了很久，无法解决

**Comment by touero** [comment]
请问你是在什么系统下面是否使用了虚拟环境呢

**Comment by touero** [comment]
我看到你目前还是使用系统的python环境，这可能与你之前安装的依赖存在冲突，你应该尝试使用虚拟环境构建
我已经更新README，请尝试按照执行，命令都是在unix-like下，windows尝试替换

- 69c41baa551eed26368af93764800f58be595461
- a3adb5e0fa18f4ee20b14a03cbfa5627f042d9b1
- 523cd7f809894049af27c71dd8d1c4fad9f25e05
- 98103f0cdc7e27cc75b1aa8b2bbb854211664bd5

**Comment by BTUJACK** [comment]
感谢您的回复，想不到您这么负责。
你应该是在苹果电脑上运行的。
我是Windows 10系统，使用sublime text编辑器直接跑起来的。我不太会使用虚拟环境。（不用虚拟环境就无法解决报错吗？好奇）
这种情况需要替换什么地方才能解决报错呢？

**Comment by touero** [comment]
> 感谢您的回复，想不到您这么负责。 你应该是在苹果电脑上运行的。 我是Windows 10系统，使用sublime text编辑器直接跑起来的。我不太会使用虚拟环境。（不用虚拟环境就无法解决报错吗？好奇） 这种情况需要替换什么地方才能解决报错呢？

- 当时最初写的时候是在windows下的，目前我在mac、linux下都能正常运行。
- 如果你的电脑上有很多的python项目，而这些项目的你所有的pip install都是安装到系统默认的地方，所有的项目都会使用这里的包。
- 如果这样，不同项目之间依赖不同版本的包就会出现不可预知的问题，即使这个项目的依赖你处理了，其他项目又会出现其他问题，这在机器学习的项目中相当常见。
- 所以请尝试使用虚拟环境，它能为每一个项目配置项目所需要的包，删除项目文件夹，相对应的依赖也会被删除。
- 你可以把虚拟环境简单地看成单独为每一个项目设置一个python解释器和pip安装包的路径，尽管它可能不是这么简单。
- 看报错信息是你的证书过期或者未安装
